### ISSUE TITLE
Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rollecode** [tomma5o/vscode-sassMap#4]
Getting "Saving '_cta-with-image.scss': Getting code actions from ''CSS Language Features'' (configure)." and suspecting this extension is causing it.

Log shows:

```
[15193:0722/123530.443651:INFO:CONSOLE(1670)] "%c  ERR color: #f33 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at WordCounter.retriveCurrentPath (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:54:28)
    at WordCounter.getNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:69:34)
    at WordCounter.updateNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:28:36)
    at WordCounterController._onEvent (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:100:27)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:821)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:767:210
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at g.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:654:482)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.444082:INFO:CONSOLE(1670)] "%cTRACE color: #888 CommandService#executeCommand setContext", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.447476:INFO:CONSOLE(1670)] "%cTRACE color: #888 CommandService#executeCommand setContext", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.551873:INFO:CONSOLE(1670)] "%c  ERR color: #f33 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at WordCounter.retriveCurrentPath (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:54:28)
    at WordCounter.getNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:69:34)
    at WordCounter.updateNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:28:36)
    at WordCounterController._onEvent (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:100:27)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:821)
    at t.ExtHostEditors.$acceptEditorPropertiesChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:768:942)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.552797:INFO:CONSOLE(1670)] "%c  ERR color: #f33 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at WordCounter.retriveCurrentPath (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:54:28)
    at WordCounter.getNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:69:34)
    at WordCounter.updateNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:28:36)
    at WordCounterController._onEvent (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:100:27)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:821)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:767:210
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at g.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:654:482)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.552907:INFO:CONSOLE(1670)] "%cTRACE color: #888 CommandService#executeCommand setContext", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.615537:INFO:CONSOLE(1670)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.focusActiveEditorGroup", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.708660:INFO:CONSOLE(1670)] "%c  ERR color: #f33 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at WordCounter.retriveCurrentPath (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:54:28)
    at WordCounter.getNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:69:34)
    at WordCounter.updateNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:28:36)
    at WordCounterController._onEvent (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:100:27)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:821)
    at t.ExtHostEditors.$acceptEditorPropertiesChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:768:942)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.709337:INFO:CONSOLE(1670)] "%c  ERR color: #f33 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at WordCounter.retriveCurrentPath (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:54:28)
    at WordCounter.getNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:69:34)
    at WordCounter.updateNestedRules (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:28:36)
    at WordCounterController._onEvent (/Users/rolle/Projects/vscode-settings/.vscode/extensions/tomma5o.sassyah-0.0.5/out/src/extension.js:100:27)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:821)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:767:210
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at g.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:654:482)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[15193:0722/123530.709486:INFO:CONSOLE(1670)] "%cTRACE color: #888 CommandService#executeCommand setContext", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
```

**Comment by tomma5o** [comment]
Hi @ronilaukkarinen,

Thanks for reporting this!

Does this block you from saving the file?
If yes, can you send/attach me your sass file that was happening the error you've reported?

**Comment by rollecode** [comment]
I have stopped using this plugin after July but as far as I can remember it happened with any file. If not reproducable enough, feel free to close this issue. Yes, it prevents to save the file.

**Comment by tomma5o** [comment]
Oh seems strange, I'm using my extension from 3y never encounter this problem.

Just for reference if anyone encounters this issue.

Here a guide for activating the breadcrumbs natively in VSCode ;)
https://dev.to/vscode/vscode-breadcrumbs-are-here-jkn
